home_cenotes:
    path: /home
    defaults: { _controller: AppBundle:Cenote:index }

new_cenote:
    path: /register-cenote
    defaults: { _controller: AppBundle:Cenote:newCenote }

cenote_profile:
    path: /cenote/{id}
    defaults: { _controller: AppBundle:Cenote:cenote, id:null }