home_cenotes:
    path: /home
    defaults: { _controller: AppBundle:Cenote:index }

new_cenote:
    path: /register-cenote
    defaults: { _controller: AppBundle:Cenote:newCenote }

cenote_profile:
    path: /cenote/{id}
    defaults: { _controller: AppBundle:Cenote:cenote, id:null }

cenotes_edit:
    path: /editar-cenote
    defaults: { _controller: AppBundle:Cenote:editCenote }

upload_images:
    path: /subir-imagenes
    defaults: { _controller: AppBundle:Cenote:uploadImages }

uploading_images:
    path: /subiendo-imagenes/{id}
    defaults: { _controller: AppBundle:Cenote:uploadingImages, id:null }