BackendBundle\Entity\Image:
    type: entity
    table: images
    indexes:
        fk_image_cenote:
            columns:
                - cenote_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        image:
            type: array
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        cenote:
            targetEntity: Cenote
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cenote_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
