BackendBundle\Entity\Video:
    type: entity
    table: videos
    indexes:
        fk_video_cenote:
            columns:
                - cenote_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        video:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        cenote:
            targetEntity: Cenote
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cenote_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
