BackendBundle\Entity\User:
    properties:
        name:
            - NotBlank: {message: "Este campo no puede estar vacio"}
        plastname:
            - NotBlank: {message: "Este campo no puede estar vacio"}
        mlastname:
            - NotBlank: {message: "Este campo no puede estar vacio"}
        email:
            - NotBlank: {message: "Este campo no puede estar vacio"}
            - Email:
                message: El email {{ value }} no es valido.
                checkMX: false
        password:
            - Length:
                min: 2
                minMessage: "La contraseña debe tener almenos 2 caracteres"
